# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.URLField(),
        ),
    ]
